"""Shared helpers for the anydeck dev / build scripts.

Tooling only - no application logic.
"""

from __future__ import annotations

import hashlib
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path

# --- project layout ---------------------------------------------------------

PROJECT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = PROJECT_DIR / "backend"
FRONTEND_DIR = PROJECT_DIR / "frontend"
PACKAGING_DIR = PROJECT_DIR / "packaging"
ASSETS_DIR = PROJECT_DIR / "assets"          # icon.svg, the master artwork
ICONS_DIR = ASSETS_DIR / "icons"             # generated by scripts/icons.py
RELEASE_DIR = PROJECT_DIR / "release"      # git-ignored, holds installers
DIST_DIR = PROJECT_DIR / "dist"            # PyInstaller output
WORK_DIR = PROJECT_DIR / "build"           # PyInstaller scratch
VENV_DIR = BACKEND_DIR / ".venv"

REQUIREMENTS = BACKEND_DIR / "requirements.txt"
REQUIREMENTS_DEV = BACKEND_DIR / "requirements-dev.txt"
BASE_STAMP = VENV_DIR / ".deps-stamp"
DEV_STAMP = VENV_DIR / ".deps-dev-stamp"

APP_NAME = "anydeck"
BACKEND_HOST = "127.0.0.1"
BACKEND_PORT = 8765
FRONTEND_PORT = 5173

VERSION_RE = re.compile(r"^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?$")


# --- console helpers --------------------------------------------------------


def info(message: str) -> None:
    print(f"==> {message}")


def warn(message: str) -> None:
    print(f"warning: {message}")


def fail(message: str) -> "None":
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def ask(question: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{question}{suffix}: ").strip()
    except EOFError:
        answer = ""
    return answer or default


def run(command: list, cwd: Path | None = None, **kwargs) -> subprocess.CompletedProcess:
    print(f"    $ {' '.join(str(part) for part in command)}")
    return subprocess.run(command, cwd=str(cwd) if cwd else None, check=True, **kwargs)


# --- versions ---------------------------------------------------------------


def is_valid_version(version: str) -> bool:
    return bool(VERSION_RE.match(version))


def prompt_version() -> str:
    while True:
        version = ask("Version to build (e.g. v1.0.0)")
        if is_valid_version(version):
            return version
        print("Invalid version. Expected format: v<major>.<minor>.<patch>[-suffix]")


# --- platform ---------------------------------------------------------------


def platform_key() -> str:
    if sys.platform == "darwin":
        return "macos"
    if sys.platform.startswith("win"):
        return "windows"
    return "linux"


def arch_key() -> str:
    machine = platform.machine().lower()
    return {"amd64": "x86_64", "arm64": "arm64", "aarch64": "arm64"}.get(machine, machine)


# --- toolchain --------------------------------------------------------------


def venv_python() -> Path:
    if platform_key() == "windows":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def npm_executable() -> str:
    found = shutil.which("npm")
    if not found:
        fail("npm not found. Install Node.js: https://nodejs.org")
    return found


def _requirements_fingerprint(files: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in files:
        digest.update(path.read_bytes() if path.exists() else b"")
    return digest.hexdigest()


def ensure_backend_deps(include_dev: bool = False) -> Path:
    """Create the virtual environment if needed and install requirements."""
    if not venv_python().exists():
        info(f"Creating virtual environment in {VENV_DIR.relative_to(PROJECT_DIR)}")
        run([sys.executable, "-m", "venv", str(VENV_DIR)])

    files = [REQUIREMENTS]
    if include_dev and REQUIREMENTS_DEV.exists():
        files.append(REQUIREMENTS_DEV)

    fingerprint = _requirements_fingerprint(files)
    stamp = DEV_STAMP if include_dev else BASE_STAMP
    if stamp.exists() and stamp.read_text().strip() == fingerprint:
        return venv_python()

    info("Installing backend dependencies")
    command = [str(venv_python()), "-m", "pip", "install", "--quiet"]
    for path in files:
        command += ["-r", str(path)]
    run(command)

    stamp.write_text(fingerprint)
    if include_dev:
        # The dev set is a superset, so the runtime set is satisfied as well.
        BASE_STAMP.write_text(_requirements_fingerprint([REQUIREMENTS]))
    else:
        DEV_STAMP.unlink(missing_ok=True)
    return venv_python()


def ensure_frontend_deps(ci: bool = False) -> None:
    """Install node modules if they are missing or out of date."""
    modules = FRONTEND_DIR / "node_modules"
    lockfile = FRONTEND_DIR / "package-lock.json"
    installed_lock = modules / ".package-lock.json"

    up_to_date = (
        modules.is_dir()
        and installed_lock.exists()
        and lockfile.exists()
        and installed_lock.stat().st_mtime >= lockfile.stat().st_mtime
    )
    if up_to_date:
        return

    info("Installing frontend dependencies")
    command = [npm_executable(), "ci" if (ci and lockfile.exists()) else "install"]
    run(command, cwd=FRONTEND_DIR)


def check_linux_gui_backend() -> None:
    """pywebview needs a system GUI toolkit on Linux - pip alone is not enough."""
    if platform_key() != "linux":
        return
    for module in ("gi", "PyQt6", "PySide6"):
        try:
            __import__(module)
            return
        except ImportError:
            continue
    warn(
        "pywebview has no GUI backend on this system. Install the system packages, "
        "not just the Python library:\n"
        "    Arch:   sudo pacman -S --needed webkit2gtk-4.1 python-gobject python-cairo\n"
        "    Ubuntu: sudo apt install gir1.2-webkit2-4.1 python3-gi python3-gi-cairo"
    )


# --- artifacts --------------------------------------------------------------


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def human_size(path: Path) -> str:
    size = path.stat().st_size
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024 or unit == "GB":
            return f"{size:.1f} {unit}" if unit != "B" else f"{size} B"
        size /= 1024
    return f"{size:.1f} GB"


def tool_available(name: str) -> bool:
    return shutil.which(name) is not None


def clean_directory(path: Path) -> Path:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)
    return path


def env_without_venv() -> dict:
    """Environment for subprocesses that must not inherit an activated venv."""
    environment = os.environ.copy()
    environment.pop("VIRTUAL_ENV", None)
    return environment
